# This is a basic workflow to help you get started with Actions

name: Code Style black

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev_open_district_upscaling" branch
  push:
    branches: [ "dev_open_district_upscaling" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
