name: check installation
on: push
jobs:
  Windows:
    name: Windows_test 
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up GDAL
        run: |   
          .\vcpkg search sqlite
          git clone https://github.com/alex85k/sqlite3-cmake.git
          dir
          
          git clone https://github.com/OSGeo/PROJ.git
          cmake PROJ
          git clone https://github.com/OSGeo/gdal
          cmake gdal

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
       
        
  
